### ISSUE TITLE
mds_traffic....py file problem

### ISSUE THREAD

**Issue by runsome** [paregupt/mds_traffic_monitor#3]
Running the following command will result in an error.

_# python3 /usr/local/telegraf/mds_traffic_monitor*.py -h
Traceback (most recent call last):
  File "/usr/local/telegraf/mds_traffic_monitor_high_frequency.py", line 17, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'_

If I comment out line 17 of the .py file and run it again, I get the following error.

_# python3 mds_traffic_monitor_high_frequency.py -h
Traceback (most recent call last):
  File "mds_traffic_monitor_high_frequency.py", line 18, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'_

If I comment out both lines 17 and 18 of the py file and run it again, I don't get the error, but grafana doesn't show the information from MDS. What do you think might be causing this?

**Comment by paregupt** [comment]
Looks like requests module is missing in Python. Try pip3 install requests. Try web search with this error. The same for the urllib3.

**Comment by runsome** [comment]
> Looks like requests module is missing in Python. Try pip3 install requests. Try web search with this error. The same for the urllib3.

Thank you for your reply.
The problem with the .py file was solved by installing requests and urllib3. But I still haven't solved the problem of MDS data not flowing into Grafana. Of the attached Grafana json files, the local_sys.json file shows up correctly in the dashboard, but the other three json files related to MDS don't seem to be working properly. Could you have a look at the configuration files and logs to upload?
[20210415.zip](https://github.com/paregupt/mds_traffic_monitor/files/6315424/20210415.zip)
*The IP addresses listed in the group file are masked.

**Comment by paregupt** [comment]
Can you please check logs in /var/log/telegraf/telegraf.log and the files in /var/log/telegraf/mds_*

Please share the full log files.

**Comment by runsome** [comment]
> Can you please check logs in /var/log/telegraf/telegraf.log and the files in /var/log/telegraf/mds_*
> 
> Please share the full log files.

Under /var/log/telegraf, there is a file called "mds_traffic_monitor_high_frequency_mds_group_1.log", but no file called telegraf.log is generated in any directory." mds_traffic_monitor..." file has already been uploaded earlier.

[root@centos-2 ~]# ll /var/log/telegraf/
total 0
drwxr-xr-x 2 root root 64 Apr 14 17:03 mds_traffic_monitor_high_frequency
[root@centos-2 ~]# ll /var/log/telegraf/mds_traffic_monitor_high_frequency/
total 8
-rw-r--r-- 1 root root 6504 Apr 14 17:03 mds_traffic_monitor_high_frequency_mds_group_1.log

**Comment by paregupt** [comment]
The format of the mds_group_1.txt file is not correct. Your file has

```
[Lab]
XX.XX.XX.XX,admin,Passw0rd

``` 

It must be in the following format:
```

[US]
192.168.1.1,mtm,mtm123,https,8443,False,10,mds9710
```
Check the file for detailed description of the fields.

**Comment by runsome** [comment]
> The format of the mds_group_1.txt file is not correct. Your file has
> 
> ```
> [Lab]
> XX.XX.XX.XX,admin,Passw0rd
> ```
> 
> It must be in the following format:
> 
> ```
> 
> [US]
> 192.168.1.1,mtm,mtm123,https,8443,False,10,mds9710
> ```
> 
> Check the file for detailed description of the fields.

I have modified the format to the following.

[Lab]
XX.XX.XX.XX,admin,Passw0rd,https,8443,False,10,mds9132t

But the data from MDS is not flowing to Grafana. should I restart the Grafana, InfluxDB and Telegraf services?

**Comment by runsome** [comment]
Grafana is not able to recognize MDS.
![WS000076](https://user-images.githubusercontent.com/82512793/114825490-4255b080-9e01-11eb-942b-0d9bdf47662c.JPG)

**Comment by paregupt** [comment]
Please share the log files again. Please share the content of telegraf.conf.
Just to be safe, restart telegraf.

**Comment by runsome** [comment]
> Please share the log files again. Please share the content of telegraf.conf.
> Just to be safe, restart telegraf.

Thank you for the reply. Uploaded all relevant files.
[20210416.zip](https://github.com/paregupt/mds_traffic_monitor/files/6322044/20210416.zip)
*The IP addresses listed in the group file are masked.

**Comment by paregupt** [comment]
The logfile shows the following error. 

```


2021-04-14 17:03:03,087 - ERROR - Exception: name 'urllib3' is not defined
Traceback (most recent call last):
  File "/usr/local/telegraf/mds_traffic_monitor_high_frequency.py", line 2310, in get_switch_stats
    rsp = future.result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/telegraf/mds_traffic_monitor_high_frequency.py", line 2257, in connect_and_pull_stats
    dispatcher)
  File "/usr/local/telegraf/mds_traffic_monitor_high_frequency.py", line 2080, in mds_nxapi_connect
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
NameError: name 'urllib3' is not defined
2021-04-14 17:03:03,089 - ERROR - Exception: name 'urllib3' is not defined
```

Try installing urllib3 module.

pip3 install urllib3

**Comment by runsome** [comment]
> The logfile shows the following error.
> 
> ```
> 
> 
> 2021-04-14 17:03:03,087 - ERROR - Exception: name 'urllib3' is not defined
> Traceback (most recent call last):
>   File "/usr/local/telegraf/mds_traffic_monitor_high_frequency.py", line 2310, in get_switch_stats
>     rsp = future.result()
>   File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 425, in result
>     return self.__get_result()
>   File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
>     raise self._exception
>   File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/local/telegraf/mds_traffic_monitor_high_frequency.py", line 2257, in connect_and_pull_stats
>     dispatcher)
>   File "/usr/local/telegraf/mds_traffic_monitor_high_frequency.py", line 2080, in mds_nxapi_connect
>     urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
> NameError: name 'urllib3' is not defined
> 2021-04-14 17:03:03,089 - ERROR - Exception: name 'urllib3' is not defined
> ```
> 
> Try installing urllib3 module.
> 
> pip3 install urllib3

I have reinstalled urllib3 after the above error. Today I tried to install urllib3 again, but it says it is already installed. The following are the logs of the urllib3 installation I did the other day and the log of the reinstallation today.

--- reinstall urllib3 in last week ---
# sudo pip3.6 install urllib3
[2021-04-15 13:20:32.416] WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3.6 install --user` instead.
[2021-04-15 13:20:32.485] Collecting urllib3
[2021-04-15 13:20:35.045]   Downloading https://files.pythonhosted.org/packages/09/c6/d3e3abe5b4f4f16cf0dfc9240ab7ce10c2baa0e268989a4e3ec19e90c84e/urllib3-1.26.4-py2.py3-none-any.whl (153kB)
[2021-04-15 13:20:35.104]     6% |???                             | 10kB 149kB/s eta 0:00:01    13% |?????                           | 20kB 296kB/s eta 0:00:01    20% |???????                         | 30kB 221kB/s eta 0:00:01    26% |?????????                       | 40kB 227kB/s eta 0:00:01    33% |???????????                     | 51kB 283kB/s eta 0:00:01    40% |?????????????                   | 61kB 294kB/s eta 0:00:01    46% |???????????????                 | 71kB 334kB/s eta 0:00:01    53% |?????????????????               | 81kB 361kB/s eta 0:00:01    60% |????????????????????            | 92kB 368kB/s eta 0:00:01    66% |??????????????????????          | 102kB 403kB/s eta 0:00:01    73% |????????????????????????        | 112kB 512kB/s eta 0:00:01    80% |??????????????????????????      | 122kB 480kB/s eta 0:00:01    86% |????????????????????????????    | 133kB 451kB/s eta 0:00:01    93% |??????????????????????????????  | 143kB 520kB/s eta 0:00:01    100% |????????????????????????????????| 153kB 455kB/s 
[2021-04-15 13:20:35.524] Installing collected packages: urllib3
[2021-04-15 13:20:35.567] Successfully installed urllib3-1.26.4

--- Today ---
# pip3 install urllib3
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Requirement already satisfied: urllib3 in /usr/local/lib/python3.6/site-packages

**Comment by paregupt** [comment]
please send me an email. I will look into your environment. email is same as my github id at cisco

**Comment by runsome** [comment]
> please send me an email. I will look into your environment. email is same as my github id at cisco
 I send email to you from dell.com.
Thank you!

**Comment by paregupt** [comment]
Looks like permission issue. Telegraf service is run by telegraf user. The /usr/local/telegraf directory and its contents must be owned by telegraf:wheel. If you run the MTM collector manaully, it is possible that that log files in /var/log/telegraf are created by the your user (for example root). Delete the log file or change the ownership. If not, telegraf user won't be able to write and fail.

Some more details: https://www.since2k7.com/blog/2020/02/29/cisco-ucs-monitoring-using-grafana-influxdb-telegraf-utm-installation/#Verification_of_ucs_traffic_monitorpy

I am not a Linux sysadmin. Maybe there are better approaches but this what I am aware.
